name: CI
on:
  pull_request:
jobs:
  ciJvms:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        java: [ '17', '21' ]
    steps:
      - uses: actions/checkout@v4.2.1
        with:
          fetch-depth: 100
      - name: Fetch tags
        run: git fetch --depth=100 origin +refs/tags/*:refs/tags/*
      - uses: actions/setup-java@v4.4.0
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          cache: 'sbt'
      - run: |
          curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          chmod +x /usr/local/bin/docker-compose
      - name: sbt ci ${{ github.ref }}
        run: ./sbt ci

  ci:
    if: always()
    runs-on: ubuntu-24.04
    needs: [ ciJvms ]
    steps:
      - uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
