name: Release
on:
  push:
    branches: [ master ]
  release:
    types: [ published ]
jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3.0.0
        with:
          fetch-depth: 0
      - uses: olafurpg/setup-scala@v13
        with:
          java-version: adopt@1.8
      - name: Coursier cache
        uses: coursier/cache-action@v6
      - name: sbt cipublish ${{ github.ref }}
        run: >
          ./sbt cipublish ; tree ideal-voting-contract/target/scala-2.13-openapi ; unzip -vl ~/.ivy2/local/cz.idealiste/ideal-voting-contract_2.13/*/docs/ideal-voting-contract_2.13-javadoc.jar ; unzip -vl ~/work/ideal-voting-backend/ideal-voting-backend/target/sonatype-staging/*/cz/idealiste/ideal-voting-contract_2.13/*/ideal-voting-contract_2.13-*-javadoc.jar
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
