name: Release
on:
  push:
    branches: [ master ]
  release:
    types: [ published ]
jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4.1.0
        with:
          distribution: 'temurin'
          java-version: 8
          cache: 'sbt'
      - name: sbt cipublish ${{ github.ref }}
        run: ./sbt cipublish
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
